{{ config(materialized='table') }}

-- Calendar dimension, 2020-01-01 .. 2030-12-31, generated by date_spine.
-- date_sk is the smart integer key YYYYMMDD, matching the *_date -> date_sk
-- derivation used by every fact.

with days as (
    {{ dbt_utils.date_spine(
        datepart="day",
        start_date="cast('2020-01-01' as date)",
        end_date="cast('2031-01-01' as date)"
    ) }}
)

select
    to_char(date_day, 'YYYYMMDD')::int   as date_sk,
    date_day::date                       as date_day,
    extract(year   from date_day)::int   as year,
    extract(quarter from date_day)::int  as quarter,
    extract(month  from date_day)::int   as month,
    to_char(date_day, 'Mon')             as month_name,
    extract(day    from date_day)::int   as day_of_month,
    extract(isodow from date_day)::int   as iso_day_of_week,
    to_char(date_day, 'Dy')              as day_name,
    (extract(isodow from date_day) in (6, 7)) as is_weekend
from days
