CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS marts_core;
CREATE SCHEMA IF NOT EXISTS marts_marketing;
CREATE SCHEMA IF NOT EXISTS marts_operations;
CREATE SCHEMA IF NOT EXISTS marts_recon;
